2023-03-27 13:36:37,826 INFO    MainThread:2057640 [wandb_setup.py:_flush():71] setting env: {}
2023-03-27 13:36:37,826 INFO    MainThread:2057640 [wandb_setup.py:_flush():71] setting login settings: {}
2023-03-27 13:36:37,826 INFO    MainThread:2057640 [wandb_init.py:_log_setup():357] Logging user logs to /home/soheil/DRL-Bench/drl/testjax/wandb/run-20230327_133637-20t0fvre/logs/debug.log
2023-03-27 13:36:37,826 INFO    MainThread:2057640 [wandb_init.py:_log_setup():358] Logging internal logs to /home/soheil/DRL-Bench/drl/testjax/wandb/run-20230327_133637-20t0fvre/logs/debug-internal.log
2023-03-27 13:36:37,826 INFO    MainThread:2057640 [wandb_init.py:init():390] calling init triggers
2023-03-27 13:36:37,826 INFO    MainThread:2057640 [wandb_init.py:init():395] wandb.init called with sweep_config: {}
config: {}
2023-03-27 13:36:37,826 INFO    MainThread:2057640 [wandb_init.py:init():435] starting backend
2023-03-27 13:36:37,826 INFO    MainThread:2057640 [backend.py:_multiprocessing_setup():94] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-03-27 13:36:37,832 INFO    MainThread:2057640 [backend.py:ensure_launched():198] starting backend process...
2023-03-27 13:36:37,833 INFO    MainThread:2057640 [backend.py:ensure_launched():203] started backend process with pid: 2058706
2023-03-27 13:36:37,833 INFO    MainThread:2057640 [wandb_init.py:init():444] backend started and connected
2023-03-27 13:36:37,833 INFO    MainThread:2057640 [wandb_init.py:init():503] updated telemetry
2023-03-27 13:36:37,837 INFO    MainThread:2057640 [wandb_init.py:init():533] communicating current version
2023-03-27 13:36:38,314 INFO    MainThread:2057640 [wandb_init.py:init():538] got version response upgrade_message: "wandb version 0.14.0 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2023-03-27 13:36:38,314 INFO    MainThread:2057640 [wandb_init.py:init():548] communicating run to backend with 30 second timeout
2023-03-27 13:37:08,314 INFO    MainThread:2057640 [interface.py:_communicate_run():903] couldn't get run from backend
2023-03-27 13:37:08,314 ERROR   MainThread:2057640 [wandb_init.py:init():553] backend process timed out
2023-03-27 13:37:08,314 ERROR   MainThread:2057640 [wandb_init.py:init():562] encountered error: Error communicating with wandb process
try: wandb.init(settings=wandb.Settings(start_method='fork'))
or:  wandb.init(settings=wandb.Settings(start_method='thread'))
For more info see: https://docs.wandb.ai/library/init#init-start-error
2023-03-27 13:37:08,322 ERROR   MainThread:2057640 [wandb_init.py:init():897] error
Traceback (most recent call last):
  File "/home/soheil/miniconda3/envs/bench/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 870, in init
    run = wi.init()
  File "/home/soheil/miniconda3/envs/bench/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 566, in init
    backend.cleanup()
  File "/home/soheil/miniconda3/envs/bench/lib/python3.10/site-packages/wandb/sdk/backend/backend.py", line 227, in cleanup
    self.interface.join()
  File "/home/soheil/miniconda3/envs/bench/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 1048, in join
    super(BackendSender, self).join()
  File "/home/soheil/miniconda3/envs/bench/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 596, in join
    self._communicate_shutdown()
  File "/home/soheil/miniconda3/envs/bench/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 1045, in _communicate_shutdown
    _ = self._communicate(record)
  File "/home/soheil/miniconda3/envs/bench/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 799, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/home/soheil/miniconda3/envs/bench/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 804, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
