2023-03-27 13:42:43,892 INFO    MainThread:2074647 [wandb_setup.py:_flush():71] setting env: {}
2023-03-27 13:42:43,892 INFO    MainThread:2074647 [wandb_setup.py:_flush():71] setting login settings: {}
2023-03-27 13:42:43,892 INFO    MainThread:2074647 [wandb_init.py:_log_setup():357] Logging user logs to /home/soheil/DRL-Bench/drl/testjax/wandb/run-20230327_134243-3enlfg5h/logs/debug.log
2023-03-27 13:42:43,892 INFO    MainThread:2074647 [wandb_init.py:_log_setup():358] Logging internal logs to /home/soheil/DRL-Bench/drl/testjax/wandb/run-20230327_134243-3enlfg5h/logs/debug-internal.log
2023-03-27 13:42:43,892 INFO    MainThread:2074647 [wandb_init.py:init():390] calling init triggers
2023-03-27 13:42:43,892 INFO    MainThread:2074647 [wandb_init.py:init():395] wandb.init called with sweep_config: {}
config: {}
2023-03-27 13:42:43,892 INFO    MainThread:2074647 [wandb_init.py:init():435] starting backend
2023-03-27 13:42:43,892 INFO    MainThread:2074647 [backend.py:_multiprocessing_setup():94] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-03-27 13:42:43,898 INFO    MainThread:2074647 [backend.py:ensure_launched():198] starting backend process...
2023-03-27 13:42:43,898 INFO    MainThread:2074647 [backend.py:ensure_launched():203] started backend process with pid: 2075671
2023-03-27 13:42:43,899 INFO    MainThread:2074647 [wandb_init.py:init():444] backend started and connected
2023-03-27 13:42:43,899 INFO    MainThread:2074647 [wandb_init.py:init():503] updated telemetry
2023-03-27 13:42:43,903 INFO    MainThread:2074647 [wandb_init.py:init():533] communicating current version
2023-03-27 13:42:44,392 INFO    MainThread:2074647 [wandb_init.py:init():538] got version response upgrade_message: "wandb version 0.14.0 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2023-03-27 13:42:44,392 INFO    MainThread:2074647 [wandb_init.py:init():548] communicating run to backend with 30 second timeout
2023-03-27 13:42:44,556 INFO    MainThread:2074647 [wandb_init.py:init():576] starting run threads in backend
2023-03-27 13:42:46,931 INFO    MainThread:2074647 [wandb_run.py:_console_start():1693] atexit reg
2023-03-27 13:42:46,932 INFO    MainThread:2074647 [wandb_run.py:_redirect():1567] redirect: SettingsConsole.REDIRECT
2023-03-27 13:42:46,932 INFO    MainThread:2074647 [wandb_run.py:_redirect():1572] Redirecting console.
2023-03-27 13:42:46,934 INFO    MainThread:2074647 [wandb_run.py:_redirect():1628] Redirects installed.
2023-03-27 13:42:46,934 INFO    MainThread:2074647 [wandb_init.py:init():603] run started, returning control to user process
2023-03-27 13:42:55,589 INFO    MainThread:2074647 [wandb_run.py:_atexit_cleanup():1663] got exitcode: 1
2023-03-27 13:42:55,590 INFO    MainThread:2074647 [wandb_run.py:_restore():1635] restore
2023-03-27 13:43:00,772 ERROR   MainThread:2074647 [wandb_run.py:_atexit_cleanup():1681] Problem finishing run
Traceback (most recent call last):
  File "/home/soheil/miniconda3/envs/bench/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1671, in _atexit_cleanup
    self._on_finish()
  File "/home/soheil/miniconda3/envs/bench/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1815, in _on_finish
    self.history._flush()
  File "/home/soheil/miniconda3/envs/bench/lib/python3.10/site-packages/wandb/sdk/wandb_history.py", line 59, in _flush
    self._callback(row=self._data, step=self._step)
  File "/home/soheil/miniconda3/envs/bench/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 972, in _history_callback
    self._backend.interface.publish_history(
  File "/home/soheil/miniconda3/envs/bench/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 505, in publish_history
    item.value_json = json_dumps_safer_history(v)  # type: ignore
  File "/home/soheil/miniconda3/envs/bench/lib/python3.10/site-packages/wandb/util.py", line 761, in json_dumps_safer_history
    return json.dumps(obj, cls=WandBHistoryJSONEncoder, **kwargs)
  File "/home/soheil/miniconda3/envs/bench/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/home/soheil/miniconda3/envs/bench/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/home/soheil/miniconda3/envs/bench/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/soheil/miniconda3/envs/bench/lib/python3.10/site-packages/wandb/util.py", line 728, in default
    return json.JSONEncoder.default(self, obj)
  File "/home/soheil/miniconda3/envs/bench/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ArrayImpl is not JSON serializable
